### ISSUE TITLE
Проблема с запуском.

### ISSUE THREAD

**Issue by loveuloveme** [I-SER-I/M33011Queue#1]
Не запускается.

**Comment by loveuloveme** [comment]
@VanjaRo

**Comment by loveuloveme** [comment]
@VanjaRo У тебя запускается?

**Comment by loveuloveme** [comment]
![image](https://user-images.githubusercontent.com/54083203/174332536-12411b4a-c3d0-457d-94d9-7fc4aa7f2d8a.png)

**Comment by VanjaRo** [comment]
> @VanjaRo У тебя запускается?

Да

**Comment by VanjaRo** [comment]
> Что делал для этого?
> 

Встал в очередь

**Comment by loveuloveme** [comment]
Нам нужно больше специалистов.

**Comment by loveuloveme** [comment]
@kalkolay

**Comment by loveuloveme** [comment]
@MelleRx
